language: c

sudo: required

before_install:
  - sudo apt-get install -y --no-install-recommends python-numpy-dev
  - sudo pip install --upgrade pip setuptools wheel
  - sudo pip install --only-binary=numpy,scipy numpy scipy
  - sudo pip install scikit-learn

script:
  - python setup.py test

notifications:
  email:
    on_success: change
    on_failure: change
