language: python
python:
  - 2.7
  - 3.6

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran

install:
  - pip install -U pip pip-tools
  - pip install numpy scipy scikit-learn

script:
  - python setup.py test

notifications:
  email:
    on_success: change
    on_failure: change